# 2.2 붓꽃 품종 예측하기

In [1]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier # 결정트리
from sklearn.model_selection import train_test_split # 학습데이터와 테스트데이터를 분리하는 함수

* 데이터 세트 로딩

In [5]:
import pandas as pd
import numpy as np

In [8]:
iris=load_iris() # 불꽃 데이터 세트 로딩

# iris_data는 iris데이터 셋에서 피처만으로 된 데이터를 갖고있음
iris_data=iris.data

#iris.target은 붓꽃 데이터 셋에서 레이블(결정 값)데이터를 갖고있음
iris_label=iris.target
print('iris target값:',iris_label)
print('iris target명:', iris.target_names)

# 붓꽃 데이터 셋을 자세히 보기 위해 DataFrame으로 변환
iris_df=pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df.head(3)

iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명: ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

* 학습 데이터와 테스트 데이터 세트로 분리

In [9]:
X_train, X_test, y_train, y_test=train_test_split(iris_data, iris_label,
                                                 test_size=0.2, random_state=11)
# train용 피처세트, test용 피처세트, train용 타겟세트(결정값), test용 타겟세트로 분리

* 학습 데이터 세트로 학습 수행

In [13]:
# DecisionTreeCalssifier 객체 생성
df_clf=DecisionTreeClassifier(random_state=11)

# 학습 수행
df_clf.fit(X_train,y_train)

DecisionTreeClassifier(random_state=11)

* 테스트 데이터 세트로 예측 수행

In [14]:
# 학습이 완료된 DecisionTreeClassfier객체에서 테스트 데이터 세트로 예측 수행
pred=df_clf.predict(X_test)
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

* 예측 정확도 평가

In [20]:
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test,pred)))

예측 정확도: 0.9333


# 2.3 사이킷런 내장 예제 데이터

In [22]:
iris_data=load_iris()
print(type(iris_data))

<class 'sklearn.utils.Bunch'>


In [23]:
keys=iris_data.keys()
print('붓 꽃 데이터 세트의 키들:',keys)
# data는 피처의 데이터 세트
# target은 분류 시 레이블 값, 회귀일 때는 숫자 결괏값 데이터 세트
# target_names는 개별 레이블의 이름
# feature_names는 피처의 이름
# DESCR은 데이터 세트에 대한 설명과 각 피처의 설명

붓 꽃 데이터 세트의 키들: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [29]:
print('\n feature_names의 type:',type(iris_data.feature_names))
print(' feature_names의 shape: ',len(iris_data.feature_names))
print(iris_data.feature_names) 

print('\n target_names의 type:',type(iris_data.target_names))
print(' target_names의 shape: ',len(iris_data.target_names))
print(iris_data.target_names)

print('\n data의 type:',type(iris_data.data))
print(' data의 shape: ',iris_data.data.shape)
print(iris_data['data']) #4개의 컬럼 150개의 로우인 2차원 

print('\n target type:',type(iris_data.target))
print(' target shape: ',iris_data.target.shape)
print(iris_data.target)


 feature_names의 type: <class 'list'>
 feature_names의 shape:  4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names의 type: <class 'numpy.ndarray'>
 target_names의 shape:  3
['setosa' 'versicolor' 'virginica']

 data의 type: <class 'numpy.ndarray'>
 data의 shape:  (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]


# 2.4 Model Selection 모듈 소개

* 학습 데이터와 테스트 데이터 분리 - train_test_split()

In [32]:
iris=load_iris() 
dt_clf=DecisionTreeClassifier()
train_data=iris.data
train_label=iris.target
dt_clf.fit(train_data, train_label) # fit()으로 학습

# 학습 데이터 세트로 예측 수행
pred=dt_clf.predict(train_data)
print('예측 정확도: ', accuracy_score(train_label,pred))

# train데이터로 학습 후 train데이터로 예측했으므로 정확도 1 -> X

예측 정확도:  1.0


In [33]:
iris_data=load_iris()
X_train, X_test, y_train, y_test=train_test_split(iris_data.data, iris_data.target,
                                                 test_size=0.3, random_state=121)


In [34]:
dt_clf.fit(X_train, y_train)
pred=dt_clf.predict(X_test)
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test,pred)))

예측 정확도: 0.9556


In [35]:
# 넘파이 ndarray뿐만 아니라 판다스 DataFrame/Series도 train_test_split()으로 분할 가능

In [36]:
iris_df=pd.DataFrame(iris_data.data, columns=iris_data.feature_names)
iris_df['target']=iris_data.target
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [37]:
ftr_df=iris_df.iloc[:,:-1] # :-1는 처음부터 마지막 컬럼 제외
tgt_df=iris_df.iloc[:,-1] # -1은 마지막 컬럼만 포함
X_train, X_test, y_train, y_test=train_test_split(ftr_df, tgt_df,
                                                 test_size=0.3, random_state=121)


In [38]:
print(type(X_train), type(X_test),type(y_train),type(y_test))

<class 'pandas.core.frame.DataFrame'> <class 'pandas.core.frame.DataFrame'> <class 'pandas.core.series.Series'> <class 'pandas.core.series.Series'>


In [40]:
dt_clf=DecisionTreeClassifier()
dt_clf.fit(X_train, y_train)
pred=dt_clf.predict(X_test)
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test,pred)))

예측 정확도: 0.9556
