In [1]:
import numpy as np

# 1.1.1 ndarray 기초

In [4]:
list1=[1,2,3]
array1=np.array(list1)
print(type(list1),"->",type(array1))

<class 'list'> -> <class 'numpy.ndarray'>


* ndarray의 형태(shape)와 차원

In [9]:
array1=np.array([1,2,3])
array2=np.array([[1,2,3],
               [2,3,4]])
array3=np.array([[1,2,3]])
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


* ndarray 데이터 값 타입

In [10]:
list=[1,2,'test']
array=np.array(list) #데이터 타입의 종류가 여러가지이라면
print(array, array.dtype) #정수형이 사이즈가 큰 문자열로 바뀌게 됨

['1' '2' 'test'] <U11


* astype()을 통한 타입 변환

In [13]:
array_float=np.array([1.1,2.2,3.3])
array_int=array_float.astype('int32')
print(array_int, array_int.dtype)

[1 2 3] int32


* ndarray에서 axis기반의 연산함수 수행

In [15]:
array2=np.array([[1,2,3],
                [2,3,4]])
print(array2.sum())
print(array2.sum(axis=0))
print(array2.sum(axis=1))

15
[3 5 7]
[6 9]


* ndarray를 편리하게 생성

In [18]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [20]:
zero_array=np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [21]:
one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


* ndarray의 shape을 변경-reshape()

In [22]:
array1=np.arange(10)
array2=array1.reshape(2,5)
array3=array1.reshape(5,2)

print('array1:\n',array1)
print('array2:\n',array2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


reshape()에 -1 인자값을 부여하여 특정 차원으로 고정된 가변적인 ndarray현태 변환

In [25]:
array1=np.arange(10)
array2=array1.reshape(-1,5) # 컬럼은 5로 고정, 로우는 컬럼크기에 맞춰 자동으로 변환
array3=array1.reshape(5,-1) # 로우는 5로 고정, 컬럼은 로우크기에 맞춰 자동으로 변환
array2d=array1.reshape(-1,1) # 1차원 ndarray를 2차원으로 변환, 반드시 컬럼은 1
array1d=array2d.reshape(-1,) # 2차원 ndarray를 1차원으로 변환
print('array1:\n',array1)
print('array2:\n',array2)
print('array3:\n',array3)
print('array2d:\n',array2d)
print('array1d:\n',array1d)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
array2d:
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
array1d:
 [0 1 2 3 4 5 6 7 8 9]


# 1.1.2 ndarray의 데이터 세트 선택-인덱싱(Indexing)

* 단일 값 추출

In [30]:
array1=np.arange(start=1, stop=10)
print('array1:',array1)

value=array1[2]
print('value:',value,type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3 <class 'numpy.int32'>


In [29]:
print("맨 뒤:", array1[-1])

맨 뒤: 9


In [32]:
array1[0]=9
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 9]


In [34]:
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:',array2d[0,0])
print('(row=0, col=1) index 가리키는 값:',array2d[0,1])
print('(row=1, col=0) index 가리키는 값:',array2d[1,0])
print('(row=2, col=2) index 가리키는 값:',array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


* 슬라이싱

In [36]:
print(array1d)
array2=array1d[0:3]
print(array2, type(array2))

[1 2 3 4 5 6 7 8 9]
[1 2 3] <class 'numpy.ndarray'>


In [37]:
array3=array1d[:3]
print(array3)

array4=array1d[3:]
print(array4)

array5=array1d[:]
print(array5)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [40]:
print(array2d)

print('array2d[0:2,0:2] \n', array2d[0:2,0:2])
print('array2d[1:3,0:3] \n', array2d[1:3,0:3])
print('array2d[1:3,:] \n', array2d[1:3,:])
print('array2d[:,:] \n', array2d[:,:])
print('array2d[:2,1:] \n', array2d[:2,1:])
print('array2d[:2,0] \n', array2d[:2,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2] 
 [[1 2]
 [4 5]]
array2d[1:3,0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:] 
 [[4 5 6]
 [7 8 9]]
array2d[:,:] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:] 
 [[2 3]
 [5 6]]
array2d[:2,0] 
 [1 4]


* 팬시 인덱싱

In [44]:
print(array2d)

array3=array2d[[0,1],2]
print('array2d[[0,1],2]=>',array3.tolist())

array4=array2d[[0,2],0:2]
print('array2d[[0,2],0:2]=>',array4.tolist())

array5=array2d[[0,1]]
print('array2d[[0,1]]=>',array5.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[[0,1],2]=> [3, 6]
array2d[[0,2],0:2]=> [[1, 2], [7, 8]]
array2d[[0,1]]=> [[1, 2, 3], [4, 5, 6]]


* 불린 인덱싱

In [45]:
print(array1d)

[1 2 3 4 5 6 7 8 9]


In [46]:
print(array1d>5) #조건식이 ndarray로 반환: T,F로 반환

[False False False False False  True  True  True  True]


In [47]:
array=array1d[array1d>5]
print(array)

[6 7 8 9]


# 1.1.3 행렬의 정렬-sort()와 argsort()

* 행렬의 정렬-sort()

In [51]:
org_array=np.array([3,1,9,5])
print('원본 행렬:',org_array)

# np.sort()로 정렬
sort_array1=np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:',sort_array1)
print('np.sort() 호출 후 원본 행렬:',org_array)

# ndarray.sort()로 정렬
sort_array2=org_array.sort()
org_array.sort() # 반환값 None
print('org_array.sort() 호출 후 반환된 정렬 행렬:',sort_array2)
print('org_array.sort() 호출 후 원본 행렬:',org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 정렬 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [52]:
# 내림차순으로 정렬
sort_array1_desc=np.sort(org_array)[::-1]
print(org_array,'->',sort_array1_desc)

[1 3 5 9] -> [9 5 3 1]


In [53]:
array2d=np.array([[8,12],
                 [7,1]])

sort_array2d_axis0=np.sort(array2d,axis=0)
print('로우 방향으로 정렬:\n',sort_array2d_axis0)

sort_array2d_axis1=np.sort(array2d,axis=1)
print('컬럼 방향으로 정렬:\n',sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


* 정렬된 행렬의 인덱스를 반환-ardsort()

In [57]:
org_array=np.array([3,1,9,5])
print(np.sort(org_array))

sort_indices=np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:',sort_indices)

# 내림차순
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:',np.argsort(org_array)[::-1])

[1 3 5 9]
<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [58]:
# key-value 매핑을 해야할 때 argsort()를 이용하여 key값을 정렬

name_array=np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array=np.array([78,95,84,98,88])

# score_array의 정렬된 값에 해당하는 원본 행렬 위치 인덱스를 반환하고 이를 이용하여 name_array에서 name값 추출
sort_indices=np.argsort(score_array)
print("sort indices:",sort_indices)

name_array_sort=name_array[sort_indices]
score_array_sort=score_array[sort_indices]
print(name_array_sort)
print(score_array_sort)

sort indices: [0 2 4 1 3]
['John' 'Sarah' 'Samuel' 'Mike' 'Kate']
[78 84 88 95 98]


# 1.1.4 선형대수 연산-행렬내적과 전치행렬 구하기

* 행렬 내적(행렬 곱)

In [60]:
A=np.array([[1,2,3],
           [4,5,6]])
B=np.array([[7,8],
           [9,10],
           [11,12]])

dot_product=np.dot(A,B)
print('행렬 내적 결과:\n',dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


* 전치 행렬

In [61]:
A=np.array([[1,2],
           [3,4]])
transpose_mat=np.transpose(A)
print('A의 전치 행렬:\n',transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
